const menuButton=document.querySelector('.menu-button');const navigation=document.querySelector('nav');menuButton.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});navigation.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navigation.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

const dialog=document.querySelector('.lightbox');const fullImage=dialog.querySelector('img');const caption=dialog.querySelector('p');document.querySelectorAll('.work,.challenge-card').forEach(work=>work.addEventListener('click',()=>{fullImage.src=work.dataset.full;fullImage.alt=work.dataset.title;caption.textContent=work.dataset.title;dialog.showModal()}));dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});

const excerptButton=document.querySelector('.excerpt-button');const excerpt=document.querySelector('.excerpt');excerptButton.addEventListener('click',()=>{const opening=excerpt.hidden;excerpt.hidden=!opening;excerptButton.setAttribute('aria-expanded',String(opening));excerptButton.firstChild.textContent=opening?'Fechar trecho ':'Ler um trecho '});

const progress=document.querySelector('.scroll-progress');const heroImage=document.querySelector('.hero-art img');window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max?scrollY/max:0})`;if(innerWidth>800&&heroImage)heroImage.style.transform=`translateY(${Math.min(scrollY*.08,70)}px) scale(1.07)`},{passive:true});

const aura=document.querySelector('.cursor-aura');if(matchMedia('(pointer:fine)').matches){window.addEventListener('pointermove',event=>{aura.animate({left:`${event.clientX}px`,top:`${event.clientY}px`},{duration:650,fill:'forwards'})});document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>aura.classList.add('active'));el.addEventListener('mouseleave',()=>aura.classList.remove('active'))})}
